
import javax.swing.ImageIcon;

/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
/**
 *
 * @author peckfarl
 */
public class finalgui extends javax.swing.JFrame {

    boolean red = true;
    boolean win = false;
    int[][] board = new int[7][6];

    /**
     * Creates new form finalgui
     */
    public finalgui() {
        initComponents();
        player();
        lblWinPic.setEnabled(false);
        for (int x = 0; x < 7; x++) {
            for (int y = 0; y < 6; y++) {
                board[x][y] = 0;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWinPic = new javax.swing.JLabel();
        btnX0Y0 = new javax.swing.JButton();
        btnX0Y1 = new javax.swing.JButton();
        btnX0Y2 = new javax.swing.JButton();
        btnX0Y3 = new javax.swing.JButton();
        btnX0Y4 = new javax.swing.JButton();
        btnX0Y5 = new javax.swing.JButton();
        btnX1Y0 = new javax.swing.JButton();
        btnX1Y1 = new javax.swing.JButton();
        btnX1Y2 = new javax.swing.JButton();
        btnX1Y3 = new javax.swing.JButton();
        btnX1Y4 = new javax.swing.JButton();
        btnX1Y5 = new javax.swing.JButton();
        btnX2Y0 = new javax.swing.JButton();
        btnX2Y1 = new javax.swing.JButton();
        btnX2Y2 = new javax.swing.JButton();
        btnX2Y3 = new javax.swing.JButton();
        btnX2Y4 = new javax.swing.JButton();
        btnX2Y5 = new javax.swing.JButton();
        btnX3Y0 = new javax.swing.JButton();
        btnX3Y1 = new javax.swing.JButton();
        btnX3Y2 = new javax.swing.JButton();
        btnX3Y3 = new javax.swing.JButton();
        btnX3Y4 = new javax.swing.JButton();
        btnX3Y5 = new javax.swing.JButton();
        btnX4Y0 = new javax.swing.JButton();
        btnX4Y1 = new javax.swing.JButton();
        btnX4Y2 = new javax.swing.JButton();
        btnX4Y3 = new javax.swing.JButton();
        btnX4Y4 = new javax.swing.JButton();
        btnX4Y5 = new javax.swing.JButton();
        btnX5Y0 = new javax.swing.JButton();
        btnX5Y1 = new javax.swing.JButton();
        btnX5Y2 = new javax.swing.JButton();
        btnX5Y3 = new javax.swing.JButton();
        btnX5Y4 = new javax.swing.JButton();
        btnX5Y5 = new javax.swing.JButton();
        btnX6Y0 = new javax.swing.JButton();
        btnX6Y1 = new javax.swing.JButton();
        btnX6Y2 = new javax.swing.JButton();
        btnX6Y3 = new javax.swing.JButton();
        btnX6Y4 = new javax.swing.JButton();
        btnX6Y5 = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblKeyRed = new javax.swing.JLabel();
        lblKeyBlue = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        pnlInstructions = new javax.swing.JScrollPane();
        txtInstructions = new javax.swing.JTextArea();
        lblMessage = new javax.swing.JLabel();
        lblRed = new javax.swing.JLabel();
        lblBlue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 380));
        setMinimumSize(new java.awt.Dimension(600, 380));
        setPreferredSize(new java.awt.Dimension(600, 380));
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(lblWinPic);
        lblWinPic.setBounds(90, 120, 230, 110);

        btnX0Y0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX0Y0.setContentAreaFilled(false);
        btnX0Y0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX0Y0.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX0Y0.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX0Y0.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX0Y0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX0Y0ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX0Y0);
        btnX0Y0.setBounds(10, 291, 50, 50);

        btnX0Y1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX0Y1.setContentAreaFilled(false);
        btnX0Y1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX0Y1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX0Y1.setEnabled(false);
        btnX0Y1.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX0Y1.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX0Y1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX0Y1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX0Y1);
        btnX0Y1.setBounds(10, 235, 50, 50);

        btnX0Y2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX0Y2.setContentAreaFilled(false);
        btnX0Y2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX0Y2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX0Y2.setEnabled(false);
        btnX0Y2.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX0Y2.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX0Y2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX0Y2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX0Y2);
        btnX0Y2.setBounds(10, 179, 50, 50);

        btnX0Y3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX0Y3.setContentAreaFilled(false);
        btnX0Y3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX0Y3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX0Y3.setEnabled(false);
        btnX0Y3.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX0Y3.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX0Y3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX0Y3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX0Y3);
        btnX0Y3.setBounds(10, 123, 50, 50);

        btnX0Y4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX0Y4.setContentAreaFilled(false);
        btnX0Y4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX0Y4.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX0Y4.setEnabled(false);
        btnX0Y4.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX0Y4.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX0Y4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX0Y4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX0Y4);
        btnX0Y4.setBounds(10, 67, 50, 50);

        btnX0Y5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX0Y5.setContentAreaFilled(false);
        btnX0Y5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX0Y5.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX0Y5.setEnabled(false);
        btnX0Y5.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX0Y5.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX0Y5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX0Y5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX0Y5);
        btnX0Y5.setBounds(10, 11, 50, 50);

        btnX1Y0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX1Y0.setContentAreaFilled(false);
        btnX1Y0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX1Y0.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX1Y0.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX1Y0.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX1Y0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX1Y0ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX1Y0);
        btnX1Y0.setBounds(66, 291, 50, 50);

        btnX1Y1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX1Y1.setContentAreaFilled(false);
        btnX1Y1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX1Y1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX1Y1.setEnabled(false);
        btnX1Y1.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX1Y1.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX1Y1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX1Y1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX1Y1);
        btnX1Y1.setBounds(66, 235, 50, 50);

        btnX1Y2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX1Y2.setContentAreaFilled(false);
        btnX1Y2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX1Y2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX1Y2.setEnabled(false);
        btnX1Y2.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX1Y2.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX1Y2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX1Y2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX1Y2);
        btnX1Y2.setBounds(66, 179, 50, 50);

        btnX1Y3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX1Y3.setContentAreaFilled(false);
        btnX1Y3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX1Y3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX1Y3.setEnabled(false);
        btnX1Y3.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX1Y3.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX1Y3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX1Y3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX1Y3);
        btnX1Y3.setBounds(66, 123, 50, 50);

        btnX1Y4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX1Y4.setContentAreaFilled(false);
        btnX1Y4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX1Y4.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX1Y4.setEnabled(false);
        btnX1Y4.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX1Y4.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX1Y4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX1Y4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX1Y4);
        btnX1Y4.setBounds(66, 67, 50, 50);

        btnX1Y5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX1Y5.setContentAreaFilled(false);
        btnX1Y5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX1Y5.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX1Y5.setEnabled(false);
        btnX1Y5.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX1Y5.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX1Y5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX1Y5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX1Y5);
        btnX1Y5.setBounds(66, 11, 50, 50);

        btnX2Y0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX2Y0.setContentAreaFilled(false);
        btnX2Y0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX2Y0.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX2Y0.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX2Y0.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX2Y0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX2Y0ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX2Y0);
        btnX2Y0.setBounds(122, 291, 50, 50);

        btnX2Y1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX2Y1.setContentAreaFilled(false);
        btnX2Y1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX2Y1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX2Y1.setEnabled(false);
        btnX2Y1.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX2Y1.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX2Y1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX2Y1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX2Y1);
        btnX2Y1.setBounds(122, 235, 50, 50);

        btnX2Y2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX2Y2.setContentAreaFilled(false);
        btnX2Y2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX2Y2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX2Y2.setEnabled(false);
        btnX2Y2.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX2Y2.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX2Y2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX2Y2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX2Y2);
        btnX2Y2.setBounds(122, 179, 50, 50);

        btnX2Y3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX2Y3.setContentAreaFilled(false);
        btnX2Y3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX2Y3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX2Y3.setEnabled(false);
        btnX2Y3.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX2Y3.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX2Y3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX2Y3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX2Y3);
        btnX2Y3.setBounds(122, 123, 50, 50);

        btnX2Y4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX2Y4.setContentAreaFilled(false);
        btnX2Y4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX2Y4.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX2Y4.setEnabled(false);
        btnX2Y4.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX2Y4.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX2Y4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX2Y4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX2Y4);
        btnX2Y4.setBounds(122, 67, 50, 50);

        btnX2Y5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX2Y5.setContentAreaFilled(false);
        btnX2Y5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX2Y5.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX2Y5.setEnabled(false);
        btnX2Y5.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX2Y5.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX2Y5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX2Y5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX2Y5);
        btnX2Y5.setBounds(122, 11, 50, 50);

        btnX3Y0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX3Y0.setContentAreaFilled(false);
        btnX3Y0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX3Y0.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX3Y0.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX3Y0.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX3Y0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX3Y0ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX3Y0);
        btnX3Y0.setBounds(178, 291, 50, 50);

        btnX3Y1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX3Y1.setContentAreaFilled(false);
        btnX3Y1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX3Y1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX3Y1.setEnabled(false);
        btnX3Y1.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX3Y1.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX3Y1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX3Y1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX3Y1);
        btnX3Y1.setBounds(178, 235, 50, 50);

        btnX3Y2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX3Y2.setContentAreaFilled(false);
        btnX3Y2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX3Y2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX3Y2.setEnabled(false);
        btnX3Y2.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX3Y2.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX3Y2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX3Y2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX3Y2);
        btnX3Y2.setBounds(178, 179, 50, 50);

        btnX3Y3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX3Y3.setContentAreaFilled(false);
        btnX3Y3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX3Y3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX3Y3.setEnabled(false);
        btnX3Y3.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX3Y3.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX3Y3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX3Y3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX3Y3);
        btnX3Y3.setBounds(178, 123, 50, 50);

        btnX3Y4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX3Y4.setContentAreaFilled(false);
        btnX3Y4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX3Y4.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX3Y4.setEnabled(false);
        btnX3Y4.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX3Y4.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX3Y4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX3Y4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX3Y4);
        btnX3Y4.setBounds(178, 67, 50, 50);

        btnX3Y5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX3Y5.setContentAreaFilled(false);
        btnX3Y5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX3Y5.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX3Y5.setEnabled(false);
        btnX3Y5.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX3Y5.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX3Y5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX3Y5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX3Y5);
        btnX3Y5.setBounds(178, 11, 50, 50);

        btnX4Y0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX4Y0.setContentAreaFilled(false);
        btnX4Y0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX4Y0.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX4Y0.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX4Y0.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX4Y0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX4Y0ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX4Y0);
        btnX4Y0.setBounds(234, 291, 50, 50);

        btnX4Y1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX4Y1.setContentAreaFilled(false);
        btnX4Y1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX4Y1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX4Y1.setEnabled(false);
        btnX4Y1.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX4Y1.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX4Y1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX4Y1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX4Y1);
        btnX4Y1.setBounds(234, 235, 50, 50);

        btnX4Y2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX4Y2.setContentAreaFilled(false);
        btnX4Y2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX4Y2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX4Y2.setEnabled(false);
        btnX4Y2.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX4Y2.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX4Y2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX4Y2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX4Y2);
        btnX4Y2.setBounds(234, 179, 50, 50);

        btnX4Y3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX4Y3.setContentAreaFilled(false);
        btnX4Y3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX4Y3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX4Y3.setEnabled(false);
        btnX4Y3.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX4Y3.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX4Y3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX4Y3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX4Y3);
        btnX4Y3.setBounds(234, 123, 50, 50);

        btnX4Y4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX4Y4.setContentAreaFilled(false);
        btnX4Y4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX4Y4.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX4Y4.setEnabled(false);
        btnX4Y4.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX4Y4.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX4Y4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX4Y4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX4Y4);
        btnX4Y4.setBounds(234, 67, 50, 50);

        btnX4Y5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX4Y5.setContentAreaFilled(false);
        btnX4Y5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX4Y5.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX4Y5.setEnabled(false);
        btnX4Y5.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX4Y5.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX4Y5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX4Y5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX4Y5);
        btnX4Y5.setBounds(234, 11, 50, 50);

        btnX5Y0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX5Y0.setContentAreaFilled(false);
        btnX5Y0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX5Y0.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX5Y0.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX5Y0.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX5Y0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX5Y0ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX5Y0);
        btnX5Y0.setBounds(290, 291, 50, 50);

        btnX5Y1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX5Y1.setContentAreaFilled(false);
        btnX5Y1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX5Y1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX5Y1.setEnabled(false);
        btnX5Y1.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX5Y1.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX5Y1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX5Y1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX5Y1);
        btnX5Y1.setBounds(290, 235, 50, 50);

        btnX5Y2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX5Y2.setContentAreaFilled(false);
        btnX5Y2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX5Y2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX5Y2.setEnabled(false);
        btnX5Y2.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX5Y2.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX5Y2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX5Y2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX5Y2);
        btnX5Y2.setBounds(290, 179, 50, 50);

        btnX5Y3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX5Y3.setContentAreaFilled(false);
        btnX5Y3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX5Y3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX5Y3.setEnabled(false);
        btnX5Y3.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX5Y3.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX5Y3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX5Y3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX5Y3);
        btnX5Y3.setBounds(290, 123, 50, 50);

        btnX5Y4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX5Y4.setContentAreaFilled(false);
        btnX5Y4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX5Y4.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX5Y4.setEnabled(false);
        btnX5Y4.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX5Y4.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX5Y4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX5Y4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX5Y4);
        btnX5Y4.setBounds(290, 67, 50, 50);

        btnX5Y5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX5Y5.setContentAreaFilled(false);
        btnX5Y5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX5Y5.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX5Y5.setEnabled(false);
        btnX5Y5.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX5Y5.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX5Y5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX5Y5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX5Y5);
        btnX5Y5.setBounds(290, 11, 50, 50);

        btnX6Y0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX6Y0.setContentAreaFilled(false);
        btnX6Y0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX6Y0.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX6Y0.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX6Y0.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX6Y0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX6Y0ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX6Y0);
        btnX6Y0.setBounds(346, 291, 50, 50);

        btnX6Y1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX6Y1.setContentAreaFilled(false);
        btnX6Y1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX6Y1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX6Y1.setEnabled(false);
        btnX6Y1.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX6Y1.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX6Y1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX6Y1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX6Y1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX6Y1);
        btnX6Y1.setBounds(346, 235, 50, 50);

        btnX6Y2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX6Y2.setContentAreaFilled(false);
        btnX6Y2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX6Y2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX6Y2.setEnabled(false);
        btnX6Y2.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX6Y2.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX6Y2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX6Y2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX6Y2);
        btnX6Y2.setBounds(346, 179, 50, 50);

        btnX6Y3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX6Y3.setContentAreaFilled(false);
        btnX6Y3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX6Y3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX6Y3.setEnabled(false);
        btnX6Y3.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX6Y3.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX6Y3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX6Y3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX6Y3);
        btnX6Y3.setBounds(346, 123, 50, 50);

        btnX6Y4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX6Y4.setContentAreaFilled(false);
        btnX6Y4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX6Y4.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX6Y4.setEnabled(false);
        btnX6Y4.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX6Y4.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX6Y4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX6Y4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX6Y4);
        btnX6Y4.setBounds(346, 67, 50, 50);

        btnX6Y5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_D_ButtonDefault.png"))); // NOI18N
        btnX6Y5.setContentAreaFilled(false);
        btnX6Y5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX6Y5.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/E_D_ButtonDefault.png"))); // NOI18N
        btnX6Y5.setEnabled(false);
        btnX6Y5.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX6Y5.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX6Y5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX6Y5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnX6Y5);
        btnX6Y5.setBounds(346, 11, 50, 50);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background.png"))); // NOI18N
        getContentPane().add(lblBackground);
        lblBackground.setBounds(4, 0, 400, 350);

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 204, 0));
        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/title.png"))); // NOI18N
        getContentPane().add(lblTitle);
        lblTitle.setBounds(410, 0, 180, 50);

        lblKeyRed.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblKeyRed.setText("Red = Player 1");
        getContentPane().add(lblKeyRed);
        lblKeyRed.setBounds(480, 70, 120, 15);

        lblKeyBlue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblKeyBlue.setText("Blue = Player 2");
        getContentPane().add(lblKeyBlue);
        lblKeyBlue.setBounds(480, 130, 120, 17);

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset);
        btnReset.setBounds(480, 90, 90, 40);

        txtInstructions.setBackground(new java.awt.Color(240, 240, 240));
        txtInstructions.setColumns(20);
        txtInstructions.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtInstructions.setLineWrap(true);
        txtInstructions.setRows(5);
        txtInstructions.setText("How to play:\n-Click one of the bottom circles to set your first piece.\n-Peices can only be set on circles where there is no empty space below them.\n-The game will alternate between player 1 (Red) and player 2 (Blue).\n-Victory is acheived by placing 4 peices of the same colour in a line.");
        txtInstructions.setWrapStyleWord(true);
        txtInstructions.setFocusable(false);
        txtInstructions.setMinimumSize(new java.awt.Dimension(200, 150));
        txtInstructions.setRequestFocusEnabled(false);
        pnlInstructions.setViewportView(txtInstructions);

        getContentPane().add(pnlInstructions);
        pnlInstructions.setBounds(410, 170, 180, 150);

        lblMessage.setText("Message: Red Players Turn");
        getContentPane().add(lblMessage);
        lblMessage.setBounds(410, 320, 210, 20);

        lblRed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/red.png"))); // NOI18N
        getContentPane().add(lblRed);
        lblRed.setBounds(420, 50, 50, 50);

        lblBlue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/blue.png"))); // NOI18N
        getContentPane().add(lblBlue);
        lblBlue.setBounds(420, 110, 50, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnX0Y5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX0Y5ActionPerformed
        if (red == true) {
            btnX0Y5.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[0][5] = 1;
            red = false;
        } else {
            btnX0Y5.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[0][5] = 2;
            red = true;
        }
        btnX0Y5.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX0Y5ActionPerformed

    private void btnX6Y0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX6Y0ActionPerformed
        btnX6Y1.setEnabled(true);
        if (red == true) {
            btnX6Y0.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[6][0] = 1;
            red = false;
        } else {
            btnX6Y0.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[6][0] = 2;
            red = true;
        }
        btnX6Y0.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX6Y0ActionPerformed

    private void btnX6Y1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX6Y1ActionPerformed
        btnX6Y2.setEnabled(true);
        if (red == true) {
            btnX6Y1.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[6][1] = 1;
            red = false;
        } else {
            btnX6Y1.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[6][1] = 2;
            red = true;
        }
        btnX6Y1.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX6Y1ActionPerformed

    private void btnX6Y2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX6Y2ActionPerformed
        btnX6Y3.setEnabled(true);
        if (red == true) {
            btnX6Y2.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[6][2] = 1;
            red = false;
        } else {
            btnX6Y2.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[6][2] = 2;
            red = true;
        }
        btnX6Y2.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX6Y2ActionPerformed

    private void btnX6Y3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX6Y3ActionPerformed
        btnX6Y4.setEnabled(true);
        if (red == true) {
            btnX6Y3.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[6][3] = 1;
            red = false;
        } else {
            btnX6Y3.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[6][3] = 2;
            red = true;
        }
        btnX6Y3.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX6Y3ActionPerformed

    private void btnX6Y4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX6Y4ActionPerformed
        btnX6Y5.setEnabled(true);
        if (red == true) {
            btnX6Y4.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[6][4] = 1;
            red = false;
        } else {
            btnX6Y4.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[6][4] = 2;
            red = true;
        }
        btnX6Y4.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX6Y4ActionPerformed

    private void btnX5Y0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX5Y0ActionPerformed
        btnX5Y1.setEnabled(true);
        if (red == true) {
            btnX5Y0.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[5][0] = 1;
            red = false;
        } else {
            btnX5Y0.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[5][0] = 2;
            red = true;
        }
        btnX5Y0.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX5Y0ActionPerformed

    private void btnX5Y1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX5Y1ActionPerformed
        btnX5Y2.setEnabled(true);
        if (red == true) {
            btnX5Y1.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[5][1] = 1;
            red = false;
        } else {
            btnX5Y1.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[5][1] = 2;
            red = true;
        }
        btnX5Y1.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX5Y1ActionPerformed

    private void btnX5Y2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX5Y2ActionPerformed
        btnX5Y3.setEnabled(true);
        if (red == true) {
            btnX5Y2.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[5][2] = 1;
            red = false;
        } else {
            btnX5Y2.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[5][2] = 2;
            red = true;
        }
        btnX5Y2.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX5Y2ActionPerformed

    private void btnX5Y3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX5Y3ActionPerformed
        btnX5Y4.setEnabled(true);
        if (red == true) {
            btnX5Y3.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[5][3] = 1;
            red = false;
        } else {
            btnX5Y3.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[5][3] = 2;
            red = true;
        }
        btnX5Y3.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX5Y3ActionPerformed

    private void btnX5Y4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX5Y4ActionPerformed
        btnX5Y5.setEnabled(true);
        if (red == true) {
            btnX5Y4.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[5][4] = 1;
            red = false;
        } else {
            btnX5Y4.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[5][4] = 2;
            red = true;
        }
        btnX5Y4.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX5Y4ActionPerformed

    private void btnX5Y5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX5Y5ActionPerformed
        if (red == true) {
            btnX5Y5.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[5][5] = 1;
            red = false;
        } else {
            btnX5Y5.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[5][5] = 2;
            red = true;
        }
        btnX5Y5.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX5Y5ActionPerformed

    private void btnX6Y5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX6Y5ActionPerformed
        if (red == true) {
            btnX6Y5.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[6][5] = 1;
            red = false;
        } else {
            btnX6Y5.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[6][5] = 2;
            red = true;
        }
        btnX6Y5.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX6Y5ActionPerformed

    private void btnX4Y0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX4Y0ActionPerformed
        btnX4Y1.setEnabled(true);
        if (red == true) {
            btnX4Y0.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[4][0] = 1;
            red = false;
        } else {
            btnX4Y0.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[4][0] = 2;
            red = true;
        }
        btnX4Y0.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX4Y0ActionPerformed

    private void btnX4Y1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX4Y1ActionPerformed
        btnX4Y2.setEnabled(true);
        if (red == true) {
            btnX4Y1.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[4][1] = 1;
            red = false;
        } else {
            btnX4Y1.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[4][1] = 2;
            red = true;
        }
        btnX4Y1.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX4Y1ActionPerformed

    private void btnX4Y2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX4Y2ActionPerformed
        btnX4Y3.setEnabled(true);
        if (red == true) {
            btnX4Y2.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[4][2] = 1;
            red = false;
        } else {
            btnX4Y2.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[4][2] = 2;
            red = true;
        }
        btnX4Y2.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX4Y2ActionPerformed

    private void btnX4Y3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX4Y3ActionPerformed
        btnX4Y4.setEnabled(true);
        if (red == true) {
            btnX4Y3.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[4][3] = 1;
            red = false;
        } else {
            btnX4Y3.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[4][3] = 2;
            red = true;
        }
        btnX4Y3.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX4Y3ActionPerformed

    private void btnX4Y4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX4Y4ActionPerformed
        btnX4Y5.setEnabled(true);
        if (red == true) {
            btnX4Y4.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[4][4] = 1;
            red = false;
        } else {
            btnX4Y4.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[4][4] = 2;
            red = true;
        }
        btnX4Y4.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX4Y4ActionPerformed

    private void btnX4Y5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX4Y5ActionPerformed
        if (red == true) {
            btnX4Y5.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[4][5] = 1;
            red = false;
        } else {
            btnX4Y5.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[4][5] = 2;
            red = true;
        }
        btnX4Y5.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX4Y5ActionPerformed

    private void btnX3Y0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX3Y0ActionPerformed
        btnX3Y1.setEnabled(true);
        if (red == true) {
            btnX3Y0.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[3][0] = 1;
            red = false;
        } else {
            btnX3Y0.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[3][0] = 2;
            red = true;
        }
        btnX3Y0.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX3Y0ActionPerformed

    private void btnX3Y1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX3Y1ActionPerformed
        btnX3Y2.setEnabled(true);
        if (red == true) {
            btnX3Y1.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[3][1] = 1;
            red = false;
        } else {
            btnX3Y1.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[3][1] = 2;
            red = true;
        }
        btnX3Y1.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX3Y1ActionPerformed

    private void btnX3Y2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX3Y2ActionPerformed
        btnX3Y3.setEnabled(true);
        if (red == true) {
            btnX3Y2.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[3][2] = 1;
            red = false;
        } else {
            btnX3Y2.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[3][2] = 2;
            red = true;
        }
        btnX3Y2.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX3Y2ActionPerformed

    private void btnX3Y3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX3Y3ActionPerformed
        btnX3Y4.setEnabled(true);
        if (red == true) {
            btnX3Y3.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[3][3] = 1;
            red = false;
        } else {
            btnX3Y3.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[3][3] = 2;
            red = true;
        }
        btnX3Y3.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX3Y3ActionPerformed

    private void btnX3Y4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX3Y4ActionPerformed
        btnX3Y5.setEnabled(true);
        if (red == true) {
            btnX3Y4.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[3][4] = 1;
            red = false;
        } else {
            btnX3Y4.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[3][4] = 2;
            red = true;
        }
        btnX3Y4.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX3Y4ActionPerformed

    private void btnX3Y5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX3Y5ActionPerformed
        if (red == true) {
            btnX3Y5.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[3][5] = 1;
            red = false;
        } else {
            btnX3Y5.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[3][5] = 2;
            red = true;
        }
        btnX3Y5.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX3Y5ActionPerformed

    private void btnX2Y0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX2Y0ActionPerformed
        btnX2Y1.setEnabled(true);
        if (red == true) {
            btnX2Y0.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[2][0] = 1;
            red = false;
        } else {
            btnX2Y0.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[2][0] = 2;
            red = true;
        }
        btnX2Y0.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX2Y0ActionPerformed

    private void btnX2Y1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX2Y1ActionPerformed
        btnX2Y2.setEnabled(true);
        if (red == true) {
            btnX2Y1.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[2][1] = 1;
            red = false;
        } else {
            btnX2Y1.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[2][1] = 2;
            red = true;
        }
        btnX2Y1.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX2Y1ActionPerformed

    private void btnX2Y2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX2Y2ActionPerformed
        btnX2Y3.setEnabled(true);
        if (red == true) {
            btnX2Y2.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[2][2] = 1;
            red = false;
        } else {
            btnX2Y2.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[2][2] = 2;
            red = true;
        }
        btnX2Y2.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX2Y2ActionPerformed

    private void btnX2Y3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX2Y3ActionPerformed
        btnX2Y4.setEnabled(true);
        if (red == true) {
            btnX2Y3.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[2][3] = 1;
            red = false;
        } else {
            btnX2Y3.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[2][3] = 2;
            red = true;
        }
        btnX2Y3.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX2Y3ActionPerformed

    private void btnX2Y4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX2Y4ActionPerformed
        btnX2Y5.setEnabled(true);
        if (red == true) {
            btnX2Y4.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[2][4] = 1;
            red = false;
        } else {
            btnX2Y4.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[2][4] = 2;
            red = true;
        }
        btnX2Y4.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX2Y4ActionPerformed

    private void btnX2Y5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX2Y5ActionPerformed
        if (red == true) {
            btnX2Y5.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[2][5] = 1;
            red = false;
        } else {
            btnX2Y5.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[2][5] = 2;
            red = true;
        }
        btnX2Y5.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX2Y5ActionPerformed

    private void btnX1Y0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX1Y0ActionPerformed
        btnX1Y1.setEnabled(true);
        if (red == true) {
            btnX1Y0.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[1][0] = 1;
            red = false;
        } else {
            btnX1Y0.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[1][0] = 2;
            red = true;
        }
        btnX1Y0.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX1Y0ActionPerformed

    private void btnX1Y1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX1Y1ActionPerformed
        btnX1Y2.setEnabled(true);
        if (red == true) {
            btnX1Y1.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[1][1] = 1;
            red = false;
        } else {
            btnX1Y1.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[1][1] = 2;
            red = true;
        }
        btnX1Y1.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX1Y1ActionPerformed

    private void btnX1Y2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX1Y2ActionPerformed
        btnX1Y3.setEnabled(true);
        if (red == true) {
            btnX1Y2.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[1][2] = 1;
            red = false;
        } else {
            btnX1Y2.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[1][2] = 2;
            red = true;
        }
        btnX1Y2.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX1Y2ActionPerformed

    private void btnX1Y3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX1Y3ActionPerformed
        btnX1Y4.setEnabled(true);
        if (red == true) {
            btnX1Y3.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[1][3] = 1;
            red = false;
        } else {
            btnX1Y3.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[1][3] = 2;
            red = true;
        }
        btnX1Y3.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX1Y3ActionPerformed

    private void btnX1Y4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX1Y4ActionPerformed
        btnX1Y5.setEnabled(true);
        if (red == true) {
            btnX1Y4.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[1][4] = 1;
            red = false;
        } else {
            btnX1Y4.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[1][4] = 2;
            red = true;
        }
        btnX1Y4.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX1Y4ActionPerformed

    private void btnX1Y5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX1Y5ActionPerformed
        if (red == true) {
            btnX1Y5.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[1][5] = 1;
            red = false;
        } else {
            btnX1Y5.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[1][5] = 2;
            red = true;
        }
        btnX1Y5.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX1Y5ActionPerformed

    private void btnX0Y0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX0Y0ActionPerformed
        btnX0Y1.setEnabled(true);
        if (red == true) {
            btnX0Y0.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[0][0] = 1;
            red = false;
        } else {
            btnX0Y0.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[0][0] = 2;
            red = true;
        }
        btnX0Y0.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX0Y0ActionPerformed

    private void btnX0Y1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX0Y1ActionPerformed
        btnX0Y2.setEnabled(true);
        if (red == true) {
            btnX0Y1.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[0][1] = 1;
            red = false;
        } else {
            btnX0Y1.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[0][1] = 2;
            red = true;
        }
        btnX0Y1.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX0Y1ActionPerformed

    private void btnX0Y2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX0Y2ActionPerformed
        btnX0Y3.setEnabled(true);
        if (red == true) {
            btnX0Y2.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[0][2] = 1;
            red = false;
        } else {
            btnX0Y2.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[0][2] = 2;
            red = true;
        }
        btnX0Y2.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX0Y2ActionPerformed

    private void btnX0Y3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX0Y3ActionPerformed
        btnX0Y4.setEnabled(true);
        if (red == true) {
            btnX0Y3.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[0][3] = 1;
            red = false;
        } else {
            btnX0Y3.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[0][3] = 2;
            red = true;
        }
        btnX0Y3.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX0Y3ActionPerformed

    private void btnX0Y4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX0Y4ActionPerformed
        btnX0Y5.setEnabled(true);
        if (red == true) {
            btnX0Y4.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/red.png")));
            board[0][4] = 1;
            red = false;
        } else {
            btnX0Y4.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/blue.png")));
            board[0][4] = 2;
            red = true;
        }
        btnX0Y4.setEnabled(false);
        checkWin();
    }//GEN-LAST:event_btnX0Y4ActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        btnX0Y5.setEnabled(false);
        btnX0Y5.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX0Y4.setEnabled(false);
        btnX0Y4.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX0Y3.setEnabled(false);
        btnX0Y3.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX0Y2.setEnabled(false);
        btnX0Y2.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX0Y1.setEnabled(false);
        btnX0Y1.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX0Y0.setEnabled(true);
        btnX0Y0.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX1Y5.setEnabled(false);
        btnX1Y5.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX1Y4.setEnabled(false);
        btnX1Y4.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX1Y3.setEnabled(false);
        btnX1Y3.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX1Y2.setEnabled(false);
        btnX1Y2.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX1Y1.setEnabled(false);
        btnX1Y1.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX1Y0.setEnabled(true);
        btnX1Y0.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX2Y5.setEnabled(false);
        btnX2Y5.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX2Y4.setEnabled(false);
        btnX2Y4.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX2Y3.setEnabled(false);
        btnX2Y3.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX2Y2.setEnabled(false);
        btnX2Y2.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX2Y1.setEnabled(false);
        btnX2Y1.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX2Y0.setEnabled(true);
        btnX2Y0.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX3Y5.setEnabled(false);
        btnX3Y5.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX3Y4.setEnabled(false);
        btnX3Y4.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX3Y3.setEnabled(false);
        btnX3Y3.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX3Y2.setEnabled(false);
        btnX3Y2.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX3Y1.setEnabled(false);
        btnX3Y1.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX3Y0.setEnabled(true);
        btnX3Y0.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX4Y5.setEnabled(false);
        btnX4Y5.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX4Y4.setEnabled(false);
        btnX4Y4.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX4Y3.setEnabled(false);
        btnX4Y3.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX4Y2.setEnabled(false);
        btnX4Y2.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX4Y1.setEnabled(false);
        btnX4Y1.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX4Y0.setEnabled(true);
        btnX4Y0.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX5Y5.setEnabled(false);
        btnX5Y5.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX5Y4.setEnabled(false);
        btnX5Y4.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX5Y3.setEnabled(false);
        btnX5Y3.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX5Y2.setEnabled(false);
        btnX5Y2.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX5Y1.setEnabled(false);
        btnX5Y1.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX5Y0.setEnabled(true);
        btnX5Y0.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX6Y5.setEnabled(false);
        btnX6Y5.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX6Y4.setEnabled(false);
        btnX6Y4.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX6Y3.setEnabled(false);
        btnX6Y3.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX6Y2.setEnabled(false);
        btnX6Y2.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX6Y1.setEnabled(false);
        btnX6Y1.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        btnX6Y0.setEnabled(true);
        btnX6Y0.setDisabledIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/E_D_ButtonDefault.png")));
        lblWinPic.setIcon(null);
        lblWinPic.setEnabled(false);
        lblMessage.setText("Message: Red Players Turn");
        for (int x = 0; x < 7; x++) {
            for (int y = 0; y < 6; y++) {
                board[x][y] = 0;
            }
        }
        red = true;
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    private void player() {
        red = true;
    }

    private void checkWin() {
        int winner = 0;
        //Says Whos turn it is.
        if (red == true) {
            lblMessage.setText("Message: Red Players Turn");
        } else {
            lblMessage.setText("Message: Blue Players Turn");
        }
        //Up
        for (int x = 0; x < 7; x++) {
            for (int y = 0; y < 3; y++) {
                if (board[x][y] == board[x][y + 1] && board[x][y] == board[x][y + 2] && board[x][y] == board[x][y + 3] && board[x][y] != 0) {
                    winner = board[x][y];
                }
            }
        }
        //Across
        for (int y = 0; y < 6; y++) {
            for (int x = 0; x < 4; x++) {
                if (board[x][y] == board[x + 1][y] && board[x][y] == board[x + 2][y] && board[x][y] == board[x + 3][y] && board[x][y] != 0) {
                    winner = board[x][y];
                }
            }
        }
        //diagonal right
        for (int x = 0; x < 4; x++) {
            for (int y = 0; y < 3; y++) {
                if (board[x][y] == board[x + 1][y + 1] && board[x][y] == board[x + 2][y + 2] && board[x][y] == board[x + 3][y + 3] && board[x][y] != 0) {
                    winner = board[x][y];
                }
            }
        }
        //diagonal Left
        for (int x = 6; x > 2; x--) {
            for (int y = 0; y < 3; y++) {
                if (board[x][y] == board[x - 1][y + 1] && board[x][y] == board[x - 2][y + 2] && board[x][y] == board[x - 3][y + 3] && board[x][y] != 0) {
                    winner = board[x][y];
                }
            }
        }
        //when a win condition is met, disables everythung and makes it impossible to play without pressing restart
        if (winner > 0) {
            lblMessage.setText("Message: The winner is Player " + winner);                    
            if (winner == 1) {
                lblWinPic.setEnabled(true);
                lblWinPic.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/WinPicRed.png")));
            } else if (winner == 2) {
                lblWinPic.setEnabled(true);
                lblWinPic.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/WinPicBlue.png")));
            }
            btnX0Y0.setEnabled(false);
            btnX1Y0.setEnabled(false);
            btnX2Y0.setEnabled(false);
            btnX3Y0.setEnabled(false);
            btnX4Y0.setEnabled(false);
            btnX5Y0.setEnabled(false);
            btnX6Y0.setEnabled(false);

            btnX0Y1.setEnabled(false);
            btnX1Y1.setEnabled(false);
            btnX2Y1.setEnabled(false);
            btnX3Y1.setEnabled(false);
            btnX4Y1.setEnabled(false);
            btnX5Y1.setEnabled(false);
            btnX6Y1.setEnabled(false);

            btnX0Y2.setEnabled(false);
            btnX1Y2.setEnabled(false);
            btnX2Y2.setEnabled(false);
            btnX3Y2.setEnabled(false);
            btnX4Y2.setEnabled(false);
            btnX5Y2.setEnabled(false);
            btnX6Y2.setEnabled(false);

            btnX0Y3.setEnabled(false);
            btnX1Y3.setEnabled(false);
            btnX2Y3.setEnabled(false);
            btnX3Y3.setEnabled(false);
            btnX4Y3.setEnabled(false);
            btnX5Y3.setEnabled(false);
            btnX6Y3.setEnabled(false);

            btnX0Y4.setEnabled(false);
            btnX1Y4.setEnabled(false);
            btnX2Y4.setEnabled(false);
            btnX3Y4.setEnabled(false);
            btnX4Y4.setEnabled(false);
            btnX5Y4.setEnabled(false);
            btnX6Y4.setEnabled(false);

            btnX0Y5.setEnabled(false);
            btnX1Y5.setEnabled(false);
            btnX2Y5.setEnabled(false);
            btnX3Y5.setEnabled(false);
            btnX4Y5.setEnabled(false);
            btnX5Y5.setEnabled(false);
            btnX6Y5.setEnabled(false);
        }
    }

    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;


                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(finalgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(finalgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(finalgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(finalgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new finalgui().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnX0Y0;
    private javax.swing.JButton btnX0Y1;
    private javax.swing.JButton btnX0Y2;
    private javax.swing.JButton btnX0Y3;
    private javax.swing.JButton btnX0Y4;
    private javax.swing.JButton btnX0Y5;
    private javax.swing.JButton btnX1Y0;
    private javax.swing.JButton btnX1Y1;
    private javax.swing.JButton btnX1Y2;
    private javax.swing.JButton btnX1Y3;
    private javax.swing.JButton btnX1Y4;
    private javax.swing.JButton btnX1Y5;
    private javax.swing.JButton btnX2Y0;
    private javax.swing.JButton btnX2Y1;
    private javax.swing.JButton btnX2Y2;
    private javax.swing.JButton btnX2Y3;
    private javax.swing.JButton btnX2Y4;
    private javax.swing.JButton btnX2Y5;
    private javax.swing.JButton btnX3Y0;
    private javax.swing.JButton btnX3Y1;
    private javax.swing.JButton btnX3Y2;
    private javax.swing.JButton btnX3Y3;
    private javax.swing.JButton btnX3Y4;
    private javax.swing.JButton btnX3Y5;
    private javax.swing.JButton btnX4Y0;
    private javax.swing.JButton btnX4Y1;
    private javax.swing.JButton btnX4Y2;
    private javax.swing.JButton btnX4Y3;
    private javax.swing.JButton btnX4Y4;
    private javax.swing.JButton btnX4Y5;
    private javax.swing.JButton btnX5Y0;
    private javax.swing.JButton btnX5Y1;
    private javax.swing.JButton btnX5Y2;
    private javax.swing.JButton btnX5Y3;
    private javax.swing.JButton btnX5Y4;
    private javax.swing.JButton btnX5Y5;
    private javax.swing.JButton btnX6Y0;
    private javax.swing.JButton btnX6Y1;
    private javax.swing.JButton btnX6Y2;
    private javax.swing.JButton btnX6Y3;
    private javax.swing.JButton btnX6Y4;
    private javax.swing.JButton btnX6Y5;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBlue;
    private javax.swing.JLabel lblKeyBlue;
    private javax.swing.JLabel lblKeyRed;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblRed;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWinPic;
    private javax.swing.JScrollPane pnlInstructions;
    private javax.swing.JTextArea txtInstructions;
    // End of variables declaration//GEN-END:variables
}
